#include "hal_data.h"
#include "WS2812.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    uint8_t pattern = 0;
    uint8_t _rr = 0;
    uint8_t _gg = 0;
    uint8_t _bb = 0;

    while(1)
    {
        for(volatile uint8_t i = 0; i < RGB_LED_NUMBERS; i++)
        {
            setRGB_LEDs(i, _rr, _gg, _bb);
            R_BSP_SoftwareDelay (20, BSP_DELAY_UNITS_MILLISECONDS);
        }
        pattern++;

        switch(pattern) {
            case 1:
              _rr = 255;
              _gg = 0;
              _bb = 0;
            break;

            case 2:
              _rr = 0;
              _gg = 255;
              _bb = 0;
            break;

            case 3:
              _rr = 0;
              _gg = 0;
              _bb = 255;
            break;

            case 4:
              _rr = 255;
              _gg = 255;
              _bb = 255;
            break;

            default:
              _rr = 0;
              _gg = 0;
              _bb = 0;
              pattern = 0;
            break;
        }

    #if BSP_TZ_SECURE_BUILD
        /* Enter non-secure code */
        R_BSP_NonSecureEnter();
    #endif

    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
